# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Biscred Regression Suite

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Run Docker container
      run: |
        docker run -d --name my_container -p 4444:4444 --shm-size="2g" selenium/standalone-chrome:4.21.0-20240522
    
    - name: Checkout selenium tests repository
      uses: actions/checkout@v2
      with:
        repository: mmravi99/BisCred.git
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build with Maven
      run: mvn test -Preg
    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CucumberReport
        path: ./target/*.html
    - name: Stop Docker container
      if: always()
      run: |
        docker stop my_container
        docker rm my_container
